## 283 - Demystifying Enum Data Type in Python

[Youtube](https://www.youtube.com/watch?v=ZKhwkIDbyF4)

In [1]:
from enum import Enum
import numpy as np
import pandas as pd

In [2]:
class ReportType(Enum):
    TORNADO = 1
    HAIL = 2
    WIND = 3
    FLOODING = 4

In [3]:
lats = np.random.randint(-90, 90, size=(100))
lons = np.random.randint(-180, 180, size=(100))
report_type = np.random.randint(1, 4, size=(100))

In [4]:
df = pd.DataFrame({'Latitude': lats, 'Longitude': lons, 'Report': report_type})

In [5]:
df.head()

Latitude  Longitude  Report
0        -4        -23       1
1       -68        156       1
2        24        125       1
3        23       -176       3
4       -64         -7       1

In [6]:
df['Report'] = [ReportType(r) for r in df['Report']]

In [7]:
df.head()

Latitude  Longitude              Report
0        -4        -23  ReportType.TORNADO
1       -68        156  ReportType.TORNADO
2        24        125  ReportType.TORNADO
3        23       -176     ReportType.WIND
4       -64         -7  ReportType.TORNADO

In [8]:
df[df['Report'] == ReportType.TORNADO]

Latitude  Longitude              Report
0         -4        -23  ReportType.TORNADO
1        -68        156  ReportType.TORNADO
2         24        125  ReportType.TORNADO
4        -64         -7  ReportType.TORNADO
7        -13         17  ReportType.TORNADO
9         80         53  ReportType.TORNADO
16        54        -27  ReportType.TORNADO
19        19       -129  ReportType.TORNADO
20       -75        149  ReportType.TORNADO
23        17          6  ReportType.TORNADO
24        64        145  ReportType.TORNADO
27        87        -83  ReportType.TORNADO
31       -21        132  ReportType.TORNADO
33       -56         22  ReportType.TORNADO
34       -76         -3  ReportType.TORNADO
36        -6         57  ReportType.TORNADO
39       -22         15  ReportType.TORNADO
41        50       -154  ReportType.TORNADO
43       -26        110  ReportType.TORNADO
45       -38       -131  ReportType.TORNADO
47       -78         22  ReportType.TORNADO
48       -30        171  ReportType.TORNADO
50         5        -76  ReportType.TORNADO
51        80       -175  ReportType.TORNADO
56       -40       -123  ReportType.TORNADO
59         4         73  ReportType.TORNADO
62       -88          1  ReportType.TORNADO
66       -42       -108  ReportType.TORNADO
69       -37        -33  ReportType.TORNADO
75       -25         36  ReportType.TORNADO
77        -1         -9  ReportType.TORNADO
81       -55        115  ReportType.TORNADO
86       -84        -21  ReportType.TORNADO
88       -85          7  ReportType.TORNADO
89        79         18  ReportType.TORNADO
90        80         73  ReportType.TORNADO
92       -12        -80  ReportType.TORNADO
93       -15         26  ReportType.TORNADO
95       -77        -74  ReportType.TORNADO
96        16        145  ReportType.TORNADO

In [9]:
ReportType(1)

<ReportType.TORNADO: 1>

In [10]:
def my_filter(data, agressiveness):
    """
    Fake filter for demo.
    """
    if agressiveness == 'small':
        size = 1
    elif agressiveness == 'medium':
        size = 5
    elif agressiveness == 'large':
        size = 10
    else:
        raise ValueError('Invalid Filter Agressiveness')
    return data * size

In [11]:
d = np.random.random((10))

In [12]:
my_filter(d, 'small')

array([0.27003356, 0.94171538, 0.41653638, 0.62966362, 0.38039789,
       0.34088661, 0.76712207, 0.78059836, 0.56605649, 0.27466429])

In [13]:
my_filter(d, 'large')

array([2.70033563, 9.41715384, 4.16536383, 6.29663621, 3.8039789 ,
       3.40886607, 7.67122073, 7.80598361, 5.66056486, 2.74664289])

In [14]:
my_filter(d, 'smadll')

ValueError: Invalid Filter Agressiveness

In [15]:
class FilterOptions(Enum):
    small = 1
    medium = 5
    large = 10
    
    @classmethod
    def best_for_timescale(cls, datasize):
        if datasize < 1:
            return FilterOptions.small
        elif datasize < 10:
            return FilterOptions.medium
        else:
            return FilterOptions.large

In [16]:
def my_filter(data, agressiveness):
    return data * agressiveness.value

In [17]:
my_filter(d, FilterOptions.large)

array([2.70033563, 9.41715384, 4.16536383, 6.29663621, 3.8039789 ,
       3.40886607, 7.67122073, 7.80598361, 5.66056486, 2.74664289])

In [18]:
my_filter(d, FilterOptions.best_for_timescale(0))

array([0.27003356, 0.94171538, 0.41653638, 0.62966362, 0.38039789,
       0.34088661, 0.76712207, 0.78059836, 0.56605649, 0.27466429])