## 110 - Bit-wise vs. Logical Operators and Odd Value Errors


[Youtube](https://www.youtube.com/watch?v=Y2LpwVdOpgc)

In [1]:
import numpy as np

In [2]:
temperature = 12
windspeed = 4

In [3]:
temperature <= 50 and windspeed >=3

True

In [4]:
temperature = np.array([55, 12, 5, 20])
windspeed = np.array([10, 1, 10, 3])

In [5]:
temperature <= 50 and windspeed >=3

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [6]:
temperature <= 50

array([False,  True,  True,  True])

In [7]:
windspeed >=3 

array([ True, False,  True,  True])

In [8]:
(temperature <= 50) and (windspeed >=3)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [9]:
temperature <= 50 & windspeed >=3

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [10]:
(temperature <= 50) & (windspeed >=3)

array([False, False,  True,  True])