## 90 - What is a NumPy Axis?


[Youtube](https://www.youtube.com/watch?v=GC_YlrzsNU8)

In [1]:
import numpy as np

In [2]:
grid_temperatures = np.array([[[25, 26, 27], [26, 27, 28]], [[24, 25, 26], [25, 26, 27]], [[23, 24, 25], [24, 25, 26]], [[22, 23, 24], [23, 24, 25]]])

In [3]:
timeseries_temperatures = np.array([[23, 24, 25, 26, 25, 24], [24, 25, 26, 27, 28, 29], [25, 24, 23, 22, 21, 20]])

In [4]:
timeseries_temperatures.ndim

2

In [5]:
timeseries_temperatures.min()

20

In [6]:
timeseries_temperatures[0, :]

array([23, 24, 25, 26, 25, 24])

In [7]:
timeseries_temperatures[:, 0]

array([23, 24, 25])

In [8]:
timeseries_temperatures.min(axis = 0)

array([23, 24, 23, 22, 21, 20])

In [9]:
timeseries_temperatures.min(axis = 1)

array([23, 24, 20])

In [10]:
grid_temperatures

array([[[25, 26, 27],
        [26, 27, 28]],

       [[24, 25, 26],
        [25, 26, 27]],

       [[23, 24, 25],
        [24, 25, 26]],

       [[22, 23, 24],
        [23, 24, 25]]])

In [11]:
grid_temperatures.ndim

3

In [12]:
grid_temperatures[0, :, :]

array([[25, 26, 27],
       [26, 27, 28]])

In [13]:
grid_temperatures[:, 0, :]

array([[25, 26, 27],
       [24, 25, 26],
       [23, 24, 25],
       [22, 23, 24]])

In [14]:
grid_temperatures[:, :, 0]

array([[25, 26],
       [24, 25],
       [23, 24],
       [22, 23]])

In [15]:
grid_temperatures.mean()

25.0

In [16]:
grid_temperatures.mean(axis = 0)

array([[23.5, 24.5, 25.5],
       [24.5, 25.5, 26.5]])

In [17]:
grid_temperatures.mean(axis = 1)

array([[25.5, 26.5, 27.5],
       [24.5, 25.5, 26.5],
       [23.5, 24.5, 25.5],
       [22.5, 23.5, 24.5]])

In [18]:
grid_temperatures.mean(axis = 2)

array([[26., 27.],
       [25., 26.],
       [24., 25.],
       [23., 24.]])