## 167 - Building with XArray from Scratch

[Youtube](https://www.youtube.com/watch?v=hiwDEjv2a60)

In [1]:
import xarray as xr
import numpy as np

In [2]:
x = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])
y = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]])

In [3]:
temps = np.array([[23, 23, 24, 23], [24, 24, 28, 23], [23, 22, 24, 22]])
humids = np.array([[70, 69, 69, 70], [68, 68, 60, 67], [71, 70, 70, 68]])

In [4]:
np.shape(temps)

(3, 4)

In [5]:
humidity_da = xr.DataArray(humids, dims = ['y', 'x'])
humidity_da

<xarray.DataArray (y: 3, x: 4)>
array([[70, 69, 69, 70],
       [68, 68, 60, 67],
       [71, 70, 70, 68]])
Dimensions without coordinates: y, x

In [6]:
humidity_da = xr.DataArray(humids, coords = (y[:, 0], x[0, :]))
humidity_da

<xarray.DataArray (dim_0: 3, dim_1: 4)>
array([[70, 69, 69, 70],
       [68, 68, 60, 67],
       [71, 70, 70, 68]])
Coordinates:
  * dim_0    (dim_0) int64 1 2 3
  * dim_1    (dim_1) int64 1 2 3 4

In [7]:
humidity_da = xr.DataArray(humids, coords = (y[:, 0], x[0, :]), dims = ['y', 'x'])
humidity_da

<xarray.DataArray (y: 3, x: 4)>
array([[70, 69, 69, 70],
       [68, 68, 60, 67],
       [71, 70, 70, 68]])
Coordinates:
  * y        (y) int64 1 2 3
  * x        (x) int64 1 2 3 4

In [8]:
humidity_da.name = 'Relative Humidity'
humidity_da.attrs['units'] = 'percent'
humidity_da

<xarray.DataArray 'Relative Humidity' (y: 3, x: 4)>
array([[70, 69, 69, 70],
       [68, 68, 60, 67],
       [71, 70, 70, 68]])
Coordinates:
  * y        (y) int64 1 2 3
  * x        (x) int64 1 2 3 4
Attributes:
    units:    percent

In [9]:
temps_da = xr.DataArray(temps, coords = (y[:, 0], x[0, :]), dims = ['y', 'x'])
temps_da.name = 'Air Temperature'
temps_da.attrs['units'] = 'degC'
temps_da

<xarray.DataArray 'Air Temperature' (y: 3, x: 4)>
array([[23, 23, 24, 23],
       [24, 24, 28, 23],
       [23, 22, 24, 22]])
Coordinates:
  * y        (y) int64 1 2 3
  * x        (x) int64 1 2 3 4
Attributes:
    units:    degC

In [10]:
ds = xr.Dataset({'air_temperature': (['y', 'x'], temps_da.data), 'rel_humidity': (['y', 'x'], humidity_da.data)}, coords = {'x':x[0, :], 'y':y[:, 0]})
ds

<xarray.Dataset>
Dimensions:          (y: 3, x: 4)
Coordinates:
  * x                (x) int64 1 2 3 4
  * y                (y) int64 1 2 3
Data variables:
    air_temperature  (y, x) int64 23 23 24 23 24 24 28 23 23 22 24 22
    rel_humidity     (y, x) int64 70 69 69 70 68 68 60 67 71 70 70 68

In [11]:
ds.attrs['title'] = 'My Model Output'
ds

<xarray.Dataset>
Dimensions:          (y: 3, x: 4)
Coordinates:
  * x                (x) int64 1 2 3 4
  * y                (y) int64 1 2 3
Data variables:
    air_temperature  (y, x) int64 23 23 24 23 24 24 28 23 23 22 24 22
    rel_humidity     (y, x) int64 70 69 69 70 68 68 60 67 71 70 70 68
Attributes:
    title:    My Model Output